<?php
	include("../tool/header.php");
	include("subheader.php");
?>	
	
	<h1>Le Japon : Union entre Tradition et Modernisme</h1>

	<p>Le Japon est connu pour plusieurs raisons mais les st&eacute;r&eacute;otypes montrent l&rsquo;image d&rsquo;un pays technologiquement tr&egrave;s avanc&eacute; avec une population tr&egrave;s dense avec une mentalit&eacute; propre au Japon. Pourtant ferm&eacute; &agrave; l&rsquo;Europe &agrave; l&rsquo;&egrave;re Edo, le Japon se retrouve parmi les meilleurs pays du monde au sens europ&eacute;en du terme : industrie d&eacute;velopp&eacute;, &eacute;conomie fleuri, train de vie confortable. Mais &agrave; la diff&eacute;rence des pays du Vieux Continent, le Japon pr&eacute;sente une belle dualit&eacute; entre les traditions et la modernit&eacute;. Autant la modernit&eacute; du Japon devance la plupart des technologies du monde, son respect des traditions reste n&eacute;anmoins tr&egrave;s pr&eacute;sent. Le th&eacute;&acirc;tre traditionnel, ainsi que les Geishas ou les mythes des samoura&iuml;s sont des vestiges d&rsquo;un riche pass&eacute;. L&rsquo;art sous toutes ses formes (th&eacute;&acirc;tre, films, et surtout mangas et animes) sont des vecteurs de ces traditions. Lorsqu&rsquo;on compare &agrave; l&rsquo;Europe, on remarque que la tradition s&rsquo;int&egrave;gre plus facilement dans la soci&eacute;t&eacute; japonaise dans le sens o&uacute; les mangas par exemple reprennent les histoires et l&eacute;gendes du pass&eacute; pour les remettre sur le devant de la sc&egrave;ne. </p>
	
	<h2>Le Japon : une mentalit&eacute; d&rsquo;acier &#133; </h2>
	
	<p>Point primordial, et point fort, la mentalit&eacute; japonaise semble &ecirc;tre r&eacute;gie par un code &agrave; l&rsquo;instar des samoura&iuml;s. C&rsquo;est le c&oelig;ur du Japon en ce sens o&uacute; cette mentalit&eacute; est si forte qu&rsquo;elle &laquo; se voit &raquo;. Le sens de l&rsquo;honneur ou la soumission &agrave; l&rsquo;obligation de la r&eacute;ussite poussent les japonais &agrave; se surpasser, et par la m&ecirc;me occasion d&eacute;passer les autres. Par cons&eacute;quent, les capacit&eacute;s d&rsquo;adaptation des japonais aussi bien pr&eacute;sentes chez les Yakusas, qui, comme toute organisation mafieuse, s&rsquo;adaptent aux lois et &agrave; la conjoncture, que dans l&rsquo;industrie nippone qui s&rsquo;attaque &agrave; de nombreux march&eacute;s qui r&eacute;agissent tr&egrave;s rapidement comme l&rsquo;informatique ou le multim&eacute;dia, sont surprenantes. Toyota est devenu leader de l&rsquo;automobile, Sony compte parmi les g&eacute;ants du multim&eacute;dia, le robot de Honda d&eacute;passe l&rsquo;imagination. Mais il n&rsquo;y a pas de fum&eacute;e sans feux. Ces prodigieux r&eacute;sultats sont les fruits d&rsquo;un dur labeur et le r&eacute;sultat des efforts de toute une nation. A l&rsquo;inverse de l&rsquo;Europe qui pr&ocirc;ne souvent l&rsquo;&eacute;panouissement personnel, il semblerait que les japonais d&eacute;veloppent un esprit collectif : servir son pays et servir sa nation. Ce nationalisme tr&egrave;s prononc&eacute; permet ainsi de conjuguer &agrave; merveille les diff&eacute;rents efforts de chacun et de le rendre compte sur une &eacute;chelle mondiale. Cette volont&eacute; de fer s&rsquo;apprend peut-&ecirc;tre &agrave; l&rsquo;&eacute;cole mais cette motivation profonde se retrouve beaucoup dans les univers des mangas o&uacute; souvent le protagoniste doit remuer ciel et terre pour parvenir &agrave; ses fins. Ce moteur des japonais reste et, semble-t-il, restera dans le c&oelig;ur des japonais donnant ainsi la force au Japon. </p>

	<p>Toutefois, le revers de la lame est cruel. Les hikkikomori sont des exemples de personnes qui refusent cette volont&eacute; exag&eacute;r&eacute;e de r&eacute;ussite. Un suicide est bien trop dur pour sacrifier une vie si pr&eacute;cieuse au nom de son honneur. Une force qui se r&eacute;v&egrave;le &ecirc;tre une &eacute;p&eacute;e de Damocl&egrave;s place le Japon dans une situation d&eacute;licate &agrave; l&rsquo;heure o&uacute; les loisirs doivent, et non peuvent, prendre plus d&rsquo;importance. Est-ce le d&eacute;but d&rsquo;un ralentissement in&eacute;luctable ? En effet, on s&rsquo;ouvre &agrave; l&rsquo;occident et on go&ucirc;te aux plaisirs des loisirs, concept quasi inexistant au Japon il y a quelques d&eacute;cennies. De plus, la force de travail ayant son maximum pendant un demi-si&egrave;cle, les dirigeants doivent alors s&rsquo;habituer &agrave; une population qui travaille diff&eacute;remment : les salarymens voyagent, vont dans des parcs de loisirs, profitent du temps libre. Bien s&ucirc;r on est encore tr&egrave;s loin des 35h fran&ccedil;aises. Mais je souhaite insister sur le changement : une mentalit&eacute; qui change, m&ecirc;me si c&rsquo;est dans le sens de l&rsquo;am&eacute;lioration, ne se fait pas sans damage car il y aura bien un moment o&uacute; le choc sera pr&eacute;pond&eacute;rant par rapport au reste. Reste ainsi &agrave; savoir comment le Japon s&rsquo;adaptera aux temps &agrave; venir.</p>

	<h2> &#133; Mais une culture difficilement exportable</h2>
	
	<p>A la fois omnipr&eacute;sent (qui n&rsquo;a pas un produit de marque ou de fabrication japonaise chez soi de nos jours ?) et absent (il n&rsquo;y a pas de diaspora), la culture japonaise ne s&rsquo;exporte pas facilement. Comme dit au d&eacute;but, les Japonais v&eacute;hiculent des images. Le cin&eacute;ma savoure les mythes des yakusas &agrave; la fois myst&eacute;rieux et pr&eacute;sent sur le terrain. Les Mangas et les anim&eacute;s sont plus ou moins connus &agrave; travers le monde. Les arts martiaux sont enseign&eacute;s sur les cinq continents. Le th&eacute;&acirc;tre traditionnel est connu &agrave; travers le monde entier. Toutefois, il y a une diff&eacute;rence entre conna&icirc;tre et appr&eacute;cier quand il s&rsquo;agit de la culture japonaise. En effet, nous sommes malheureusement habitu&eacute;s &agrave; une uniformisation du monde via la culture occidentale. Je prends l&rsquo;exemple des mangas. Tout le monde connait de nom Naruto ou Dragon Ball. Cependant, ces mangas se lisent aussi bien au premier degr&eacute;, ce qui en fait un bon moyen de divertissement, qu&rsquo;au second degr&eacute; lorsqu&rsquo;il s&rsquo;agit de comprendre certaines r&eacute;f&eacute;rences culturelles qui sont parfois non expliqu&eacute;es. Un dernier exemple parmi les mangas : les japonais sont tr&egrave;s forts en psychologie. En effet, un mangaka doit apprendre, ou du moins s&rsquo;inspirer, de nombreuses conventions pour faire v&eacute;hiculer certains ressentis ou sentiments. Le moe est un concept qui rend &laquo; adorable &raquo; une personne, souvent une fille, ou un objet. On peut alors lister quelques caract&eacute;ristiques des causes du moe. Certains &eacute;l&eacute;ments de base sont connus pour &ecirc;tre des fantasmes masculins, comme par exemple la lyc&eacute;enne, les maids ou les filles en maillot de bain. Jusqu&rsquo;&agrave; ici, il n&rsquo;y a rien de sorcier mais lorsqu&rsquo;on commence &agrave; avoir un certain ressenti suite &agrave; un rajout constant de <i>-desu,-desuyo,-desune</i> &agrave; la fin de chaque phrase ou face &agrave; un Zettai Ryouiki (zone de chair expos&eacute; entre le bas de la jupe et le d&eacute;but des bas) assez d&eacute;concertant, on commence &agrave; saisir des d&eacute;tails qui font qu&rsquo;on s&rsquo;attache plus &agrave; un personnage qu&rsquo;&agrave; un autre. Encore plus loin, il existe des comportements qui ont m&ecirc;me un nom. Une tsundere est une personne qui &eacute;volue au fil d&rsquo;un manga : d&rsquo;abord sous une apparence froide et s&eacute;v&egrave;re, ce personnage r&eacute;v&egrave;le ses faiblesses et surtout une g&eacute;n&eacute;rosit&eacute; au fil de la s&eacute;rie rendant le personnage particuli&egrave;rement attachant.</p>

	<p>Je me suis attard&eacute; sur ce d&eacute;tail, avec une certaine l&eacute;g&egrave;ret&eacute;, pour soulever un point. Essayer c&rsquo;est adopter. Un manga, on n&rsquo;y accroche ou on n&rsquo;y accroche pas. Pourquoi ? Parce ce que les japonais ne v&eacute;hiculent pas les messages comme dans nos bandes dessin&eacute;es. Dans un anime, il se peut que nous comprenons un &eacute;pisode sans rien comprendre de ce qui s&rsquo;est dit (&agrave; &eacute;viter quand m&ecirc;me) gr&acirc;ce &agrave; des expressions, corporelles, gestuelles ou vocales, qui semble toucher &agrave; un langage universel. Cependant, ces subtilit&eacute;s ne sont pas &eacute;videntes &agrave; communiquer rendant la culture japonaise extr&ecirc;mement complexe &agrave; comprendre pour un &eacute;tranger. &laquo; Ils sont originaux &raquo; est une phrase courante, pourtant lorsqu&rsquo;on d&eacute;couvre l&rsquo;esprit japonais en profondeur, on y apprend beaucoup.
Sur internet, il est facile de trouver des sites qui parlent de ces sp&eacute;cificit&eacute;s de la culture nippone. On y trouve alors le syndrome de Rei Ayanami, un personnage de Neon Genesis Evangelion qui a cr&eacute;&eacute; un style &agrave; elle seule, ou le th&eacute;or&egrave;me de Godzilla (plus c&rsquo;est gros, plus c&rsquo;est b&ecirc;te) dans le monde des jeux videos. Tr&egrave;s amusant &agrave; lire, on d&eacute;couvre et on est convaincu que les conventions propos&eacute;es par les japonaises rel&egrave;vent d&rsquo;une perspicacit&eacute; &eacute;tonnante ce qui n&rsquo;est pas surprenant de la part d&rsquo;un peuple aussi &laquo; s&eacute;rieux &raquo;.</p>

	<p>Un des prochaines missions du Japon serait alors de mieux communiquer sa culture &agrave; l&rsquo;&eacute;chelle internationale sans se limiter aux aprioris (manga et High-tech). Les aides ne manquent pas : partout dans le monde se trouvent des personnes, pas forc&eacute;ment japonaises, pr&ecirc;te &agrave; promouvoir cette culture aussi complexe qu&rsquo;int&eacute;ressante.</p>


<?php
	include("../tool/footer.php");
?>