Le Japon
A travers une dizaine d’exposé, certains aspects du Japon nous a été présenté. Je résume chaque exposé en quelques lignes afin d’expliciter au mieux leur contenu.
1.	La Bière au Japon
les deux marques de bière qui dominent le Japon sont l’Asahi et Sapporo. Influencées par les colonisateurs hollandais, les bières japonaises ressemblent aux bières des Pays-Bas avec toutefois les matières premières du Japon
2.	Anime Mecha
Les japonais sont très friands d’animés, souvent issus des mangas. Une catégorie particulièrement d’animés regroupe, grossièrement, tout les animes avec des robots géants, des robots qui se transforment ou des exosquelettes : on parle alors d’Anime Mecha. Ce style a été influence par de nombreux critères, historiques comme la défaite de la seconde guerre mondiale ou psychologiquement comme le désir de surpasser la faiblesse de la condition humaine.
3.	Les Geishas
Les Geishas perdurent encore au Japon. L’aspect traditionnel et cérémonial du Japon se retrouve dans la longue formation des Geishas, formation aussi stricte que codifiée. Plus souple de nos jours, les écoles de Geishas forment des japonaises à l’art de servir et certaines d’entre elles sont alors des hôtesse d’entreprises qui jouent alors le rôle de mécène.
4.	Les samouraïs
Symbole de l’honneur japonais, le samouraïs suivent le bushido (code d’honneur) dont certains éléments sont présents dans d’autres arts martiaux voire dans la société japonaise contemporaine. Il y a beaucoup de protocoles, à l’instar des Geishas qui vivent dans un univers très cérémonial, et de règles. Par exemple, pour défendre son honneur, un chef vaincu doit faire senpukku (un hara-kiri). Mais dans un pays où l’échec n’est même pas toléré, l’honneur des samouraïs resterait-il parmi l’esprit japonais ?
5.	Le problème d’aménagement au Japon
Environ 127 millions d’habitants avec une surface territoriale de 370 000 km2, le Japon est un pays fortement peuplé. Etant principalement constitué de chaine montagneuse, seul un faible pourcentage de cette surface est habitable. Tokyo compte parmi les plus grosses mégalopoles du monde avec un record de densité de population. Face à ces problèmes d’espaces, le Japon se doit de développer des solutions aussi efficaces que surprenant (parking vertical de véhicules ou parking souterrains à vélo). Des projets plus ou moins démesurés sont alors mis en places pour prévoir les problèmes de l’avenir.
6.	L’influence de la Chine sur la culture japonaise
Il suffit de voir les kanji pour comprendre l’importance de la Chine au sein de la culture japonaise. Sur de nombreux plans, aussi bien architectural qu’au niveau de la pensée en passant par l’art, la Chine présente une influence non négligeable. Ainsi l’art de la calligraphie concerne les kanji et on reconnait des similitudes au niveau des styles de calligraphies (le pinceau se tient droit, l’ordre des traits suit une convention, etc.) qu’niveau de l’histoire : l’évolution des styles chinois et japonais ne semblent pas indépendants. Les exemples qui montrent ces liens sont nombreux.
7.	Le suicide au Japon
Le suicide n’est pas perçu de la même manière au Japon qu’en Europe. Au pays du Soleil Levant, le suicide est un acte de courage qui permet d’essuyer les erreurs commises, contrairement à l’Europe qui place la suicide sous le signe de la lâcheté, représentant une refus de se battre face aux difficultés de la vie. Ainsi, une perte d’emploi est un déshonneur très affligeant et un échec d’une telle ampleur peut mener au suicide. Hélas ce type de phénomène est courant au Japon et ce « mal » continue à prendre de l’ampleur et frappe une population entière dont les mœurs ne changeront pas tout de suite.
8.	Les Yakusas
« Les Japonais aiment bien les amphétamines » d’après l’élève qui a présenté les Yakusas. A l’origine issus de milieux modestes voire défavorisés, les Yakusas recrutent depuis l’aube de leur histoire parmi tous les milieux, des bas fonds à l’intelligentsia. A la fois craints et respectés, les Yakusas sont tout de même les membres de la mafia japonaise. Organisé par quartier et possédant une hiérarchie quasi-militaire, les Yakusas vivent dans l’ombre et sont parfois des soldats de l’ombre notamment après la seconde guerre mondiale. Drogues, trafic d’armes, prostitution et industrie pornographique font parties de l’arsenal de l’industrie Yakusa. Mais face aux réprimandes du gouvernement, les Yakusas diversifient leurs activités et deviennent parfois les professionnels de la Finance ou dirigent des grosses entreprises. Demandant de plus en plus d’intellectuels capables de s’adapter à ces nouveaux secteurs, les Yakusas évoluent vers un monde moderne où ils doivent faire face à une sorte de mondialisation mafieuse : la Triade chinoise.
9.	Le théâtre traditionnel
Le théâtre traditionnel regroupe trois styles théâtraux : le Nô, la Kabuki et le bunraku. Nés sous trois ères différentes, ces trois style sont fortement soumis à des conventions issues des traditions.
10.	Le Judo
Crée en …. Par …., le Judo, littéralement « voie de la souplesse », est un art martial relativement jeune. La légende raconte qu’en hiver, le maître a vu des grosses branches de bois casser sous le poids de la neige alors que les branches souples se plient pour faire tomber la neige et reprendre ensuite leur position initiale. L’idée de profiter de la force de l’adversaire pour la retourner contre lui est née. Un combat de judo consiste simplement à faire tomber l’adversaire sur le dos. La chute prend aussi en compte la vitesse et de manière générale l’esthétique du geste, modifiant ainsi la notation puisqu’il y plusieurs gammes de points (de koka, 3pts à ippon, 10pts). 


Le Japon est connu pour plusieurs raisons mais les stéréotypes montrent l’image d’un pays technologiquement très avancé avec une population très dense avec une mentalité propre au Japon. Pourtant fermé à l’Europe à l’ère Êdo, le Japon se retrouve parmi les meilleurs pays du monde au sens européen du terme : industrie développé, économie fleuri, train de vie confortable. Mais à la différence des pays du Vieux Continent, le Japon présente une belle dualité entre les traditions et la modernité. Autant la modernité du Japon devance la plupart des pays du monde, son respect des traditions reste très présent. Le théâtre traditionnel, ainsi que les Geishas ou les mythes des samouraïs sont des vestiges d’un riche passé. L’art sous toutes ses formes (théâtre, films, et surtout mangas et animes) sont des vecteurs de ces traditions.
Un point primordial est la mentalité japonaise. C’est le cœur du Japon en ce sens où cette mentalité est si forte qu’elle « se voit ». Le sens de l’honneur ou la soumission de l’obligation de la réussite poussent les japonais à se surpasser. Par conséquent, les capacités d’adaptation aussi bien chez les Yakusas que dans l’industrie nippone est surprenante. Toyota est devenu leader de l’automobile, Sony compte parmi les géants du multimédia, le robot de Honda dépasse l’imagination. Cette volonté de fer s’apprend peut-être à l’école mais cette motivation profonde se retrouve beaucoup dans les univers du manga où souvent le protagoniste doit remuer ciel et terre pour parvenir à ses fins. Ce moteur du japonais reste et, il semble, restera dans le cœur des japonais donnant ainsi la force au Japon. Toutefois, le revers de la lame est cruel. Les hikkikomori sont des exemples de personnes qui refusent cette volonté surabondante de réussite. Un suicide est bien trop dur pour sacrifier une vie si précieuse au nom de son honneur. Une force qui se révèle être une épée de Damoclès place le Japon dans une situation délicate à l’heure où les loisirs doivent, et non peuvent, prendre plus d’importance. Est-ce le début d’un ralentissement inéluctable ?
